// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace RestClientSdkLibraryTasksApp.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Custom Error Response Definition
    /// </summary>
    public partial class ErrorResponse
    {
        /// <summary>
        /// Initializes a new instance of the ErrorResponse class.
        /// </summary>
        public ErrorResponse() { }

        /// <summary>
        /// Initializes a new instance of the ErrorResponse class.
        /// </summary>
        public ErrorResponse(int? errorNumber = default(int?), string parameterName = default(string), string parameterValue = default(string), string errorDescription = default(string))
        {
            ErrorNumber = errorNumber;
            ParameterName = parameterName;
            ParameterValue = parameterValue;
            ErrorDescription = errorDescription;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorNumber")]
        public int? ErrorNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parameterName")]
        public string ParameterName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parameterValue")]
        public string ParameterValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorDescription")]
        public string ErrorDescription { get; set; }

    }
}
