// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace RestClientSdkLibraryTasksApp.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Todo Task Creation Object
    /// </summary>
    public partial class TodoTaskCreatePayload
    {
        /// <summary>
        /// Initializes a new instance of the TodoTaskCreatePayload class.
        /// </summary>
        public TodoTaskCreatePayload() { }

        /// <summary>
        /// Initializes a new instance of the TodoTaskCreatePayload class.
        /// </summary>
        public TodoTaskCreatePayload(string taskName, bool isCompleted, string dueDate)
        {
            TaskName = taskName;
            IsCompleted = isCompleted;
            DueDate = dueDate;
        }

        /// <summary>
        /// Gets and sets the Task's Name
        /// </summary>
        [JsonProperty(PropertyName = "taskName")]
        public string TaskName { get; set; }

        /// <summary>
        /// Gets and sets the Task's status
        /// </summary>
        [JsonProperty(PropertyName = "isCompleted")]
        public bool IsCompleted { get; set; }

        /// <summary>
        /// Gets and Sets the Task's Due Date
        /// </summary>
        [JsonProperty(PropertyName = "dueDate")]
        public string DueDate { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (TaskName == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "TaskName");
            }
            if (DueDate == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "DueDate");
            }
            if (this.TaskName != null)
            {
                if (this.TaskName.Length > 30)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "TaskName", 30);
                }
                if (this.TaskName.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "TaskName", 0);
                }
            }
        }
    }
}
