// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace RestClientSdkLibrary
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for RestClientSdkLibraryClient.
    /// </summary>
    public static partial class RestClientSdkLibraryClientExtensions
    {
            /// <summary>
            /// A test endpoint
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static string GetWelcomeMessage(this IRestClientSdkLibraryClient operations)
            {
                return Task.Factory.StartNew(s => ((IRestClientSdkLibraryClient)s).GetWelcomeMessageAsync(), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// A test endpoint
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<string> GetWelcomeMessageAsync(this IRestClientSdkLibraryClient operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetWelcomeMessageWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Submit game request with human move
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// </param>
            public static object ExecuteMove(this IRestClientSdkLibraryClient operations, GameInputPayload body = default(GameInputPayload))
            {
                return Task.Factory.StartNew(s => ((IRestClientSdkLibraryClient)s).ExecuteMoveAsync(body), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Submit game request with human move
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ExecuteMoveAsync(this IRestClientSdkLibraryClient operations, GameInputPayload body = default(GameInputPayload), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ExecuteMoveWithHttpMessagesAsync(body, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
